### ISSUE TITLE
Need specification to link to from other implementations

### ISSUE THREAD

**Issue by azaroth42** [no-reply/rdf-yoda_triples#5]
Such as python:

https://github.com/azaroth42/rdflib-ytriples

**Comment by gkellogg** [comment]
I'm sensing the need for a spec, test suite and implementation report!

**Comment by no-reply** [comment]
> I'm sensing the need for a spec, test suite and implementation report!

And the obvious precursor: a working group.

Who wants to start a document?

**Comment by azaroth42** [comment]
Initial specification, based on N-Triples doc:
https://github.com/azaroth42/rdflib-ytriples/blob/master/docs/index.html
Or more usefully:
http://azaroth42.github.io/rdflib-ytriples/docs/

**Comment by gkellogg** [comment]
Nice. You beat me to it!

**Comment by jpstroop** [comment]
http://azaroth42.github.io/rdflib-ytriples/docs/#rdf-blank-nodes ++

**Comment by no-reply** [comment]
Considering this resolved.
