### ISSUE TITLE
RDF::YodaTriples fails to decompose copulae from compound predicative nominals

### ISSUE THREAD

**Issue by dmolesUC** [no-reply/rdf-yoda_triples#6]
Simple predicative nominals such as _A Jedi, Yoda is_ are handled correctly, but more complex predicative nominals embedding prepositional phrases, remain composed, e.g. _To the dark side, fear is the path_ instead of _To the dark side the path, fear is._

**Steps to reproduce:**

```
graph = RDF::Graph.new
graph << RDF::Statement(RDF::URI('http://example.org/yoda'),
                        RDF::RDFS.member,
                        RDF::URI('http://en.wikipedia.org/wiki/Galactic_Republic'))    
puts graph.dump :yodatriples
```

**Expected:** _‘Of the Galactic Republic a member Yoda is.’_

```
<http://en.wikipedia.org/wiki/Galactic_Republic>
<http://www.w3.org/2000/01/rdf-schema#member>
<http://example.org/yoda>
<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>
```

**Actual:** _‘Of the Galactic Republic Yoda is a member.’_

```
<http://en.wikipedia.org/wiki/Galactic_Republic>
<http://example.org/yoda>
<http://www.w3.org/2000/01/rdf-schema#member>
```

---

**Note:**

In defense of YodaTriples, Yoda doesn't get this right either. 

![image](https://cloud.githubusercontent.com/assets/10374934/8343354/363dc1c2-1a89-11e5-8e69-4ce47253cc12.png)

**Comment by no-reply** [comment]
This issue challenges the [official](http://www.w3.org/TR/rdf11-concepts/) [dogma](http://www.w3.org/TR/rdf11-mt/)  of the Jedi Order. I've closed it, accordingly.
